name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cache
        uses: actions/cache@v4

        with:
          path: |
            ~/.cabal
            dist-newstyle
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}

      - uses: actions/checkout@v4
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.10.3"
          cabal-version: "3.2"

      - name: Install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev libsdl2-image-dev

      - name: Update the package index
        run: cabal update

      - name: Run tests
        run: cabal test all
  doctest:
    runs-on: ubuntu-latest

    steps:
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal
            dist-newstyle
          key: ${{ runner.os }}-doctest-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}

      - uses: actions/checkout@v4
      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.10.3"
          cabal-version: "3.2"

      - name: Install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev libsdl2-image-dev

      - name: Install dependencies
        run: |
          cabal update
          cabal install doctest
      - name: Run doctests
        run: cabal repl aztecs --with-compiler=doctest
